version: 'test-{build}'
environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '8'
    - nodejs_version: '10'
platform:
  - x86
  - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
  - ps: 'Install-Product node $env:nodejs_version $env:platform'
  - ps: '$NpmVersion = (npm -v).Substring(0,1)'
  - ps: 'if($NpmVersion -eq 5) { npm install -g npm@5 }'
  - ps: npm --version
  - npm install
  - npm install winston@2.3.1
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
  - perl -v
  - ps: |-
      Invoke-WebRequest "http://fhem.de/fhem-5.8.tar.gz" -OutFile .\fhem-5.8.tar.gz;
      if (Test-Path .\fhem-5.8 )
      {
          del .\fhem-5.8 -Force -Recurse
      }
      md fhem;
      7z x .\fhem-5.8.tar.gz -r; 7z x .\fhem-5.8.tar -r;
      cd ".\fhem-5.8";
      $MyProcess = Start-Process -FilePath perl -ArgumentList ('fhem.pl','fhem.cfg') -PassThru;
      cd ..
test_script:
  - echo %cd%
  - node --version
  - npm --version
  - npm test
build: 'off'
